import json
from pathlib import Path

CITY = "Maharashtra"

city_localities = {
    "Mumbai": [
        ("Bandra", "Premium coastal neighborhood with upscale dining, nightlife, and strong corporate access", 32000, "Premium"),
        ("Bandra East", "Commercial hub adjacent to Bandra Kurla Complex with connectivity and offices", 28000, "Office"),
        ("Bandra West", "Lifestyle-rich district with boutiques, cafes, and fast access to the western suburbs", 34000, "Lifestyle"),
        ("Juhu", "Beachfront neighborhood known for luxury residences, entertainment, and high quality of life", 37000, "Premium"),
        ("Santacruz", "Well-established residential area with excellent transit and school access", 29000, "Family"),
        ("Andheri", "Major transit and entertainment corridor with strong employment and retail options", 31000, "Transit"),
        ("Andheri East", "Corporate and industrial area with easy highway access and metro connectivity", 27000, "Office"),
        ("Andheri West", "Popular residential and shopping neighborhood with nightlife and transit links", 33000, "Lifestyle"),
        ("Goregaon", "Growing suburb with malls, film studios, and improved rail connectivity", 26000, "Residential"),
        ("Goregaon East", "Emerging business and residential zone near the metro and film industry", 24000, "Residential"),
        ("Goregaon West", "Established residential neighborhoods with schools and shopping malls", 28000, "Family"),
        ("Malad", "High-density suburb with strong transit options and retail demand", 25000, "Transit"),
        ("Malad West", "Residential and commercial micro-market with beach access and urban amenities", 27000, "Mixed"),
        ("Malad East", "Affordable residential localities with easy highway and suburban rail access", 23000, "Budget"),
        ("Borivali", "Large suburban district with strong rail links, schools, and family housing", 24000, "Family"),
        ("Kandivali", "Growing western suburb with residential developments and improving transit", 22000, "Value"),
        ("Dahisar", "Affordable coastal suburb with commuter rail access and expanding housing", 20000, "Budget"),
        ("Ghatkopar", "Eastern suburb with metro connectivity and strong retail markets", 26000, "Transit"),
        ("Vikhroli", "Industrial-to-residential corridor with good work and transport access", 25000, "Mixed"),
        ("Kanjurmarg", "Emerging eastern hub with new residential towers and improved rail service", 23000, "Emerging"),
        ("Bhandup", "Well-connected suburb with strong schools, affordable housing, and transit", 21000, "Family"),
        ("Mulund", "Major northern suburb combining strong schools, offices, and civic infrastructure", 26000, "Family"),
        ("Powai", "Tech and business district centered on the lake with premium housing and strong lifestyle", 35000, "IT"),
        ("Vikhroli West", "Residential pocket with park access and good highway connectivity", 24000, "Residential"),
        ("Khar", "Established locality with shopping streets, schools, and good western line access", 31000, "Lifestyle"),
        ("Khar West", "Affluent residential market close to Juhu and Bandra with strong lifestyle scores", 34000, "Premium"),
        ("Dadar", "Central Mumbai locality with excellent train connectivity and heritage markets", 30000, "Transit"),
        ("Dadar East", "Well-connected east-side hub with theaters and civic amenities", 28000, "Mixed"),
        ("Dadar West", "Prime residential and retail zone with strong transport links", 32000, "Premium"),
        ("Lower Parel", "Corporate and luxury residential hub with premium high-rises and strong office presence", 42000, "Premium"),
        ("Worli", "High-end coastal hub with landmark towers and direct freeway access", 44000, "Premium"),
        ("Parel", "Rapidly redeveloped commercial and residential district with excellent jobs access", 36000, "Office"),
        ("Sion", "Eastern transport hub with strong train connectivity and established neighborhoods", 25000, "Transit"),
        ("Matunga", "Heritage residential area with universities, markets, and strong connectivity", 28000, "Family"),
        ("Mazgaon", "Central locality with good hospitals, schools, and access to south Mumbai", 26000, "Mixed"),
        ("Byculla", "Central south locality with museums, parks, and established residential pockets", 25000, "Family"),
        ("Cuffe Parade", "Premium southern business district near the Arabian Sea", 46000, "Premium"),
        ("Churchgate", "Financial district near Marine Drive with elite housing and coastal views", 43000, "Premium"),
        ("Colaba", "Cultural and tourist district with high-end retail and heritage appeal", 39000, "Lifestyle"),
        ("Nariman Point", "Iconic business district with premium offices and sea views", 47000, "Office"),
        ("Malabar Hill", "One of Mumbai’s most prestigious residential addresses", 50000, "UltraPremium"),
        ("Bandra Kurla Complex", "Major financial district with premium office towers and strong connectivity", 45000, "Office"),
        ("Nerul", "Planned node of Navi Mumbai with good schools, transit, and residential choice", 24000, "Family"),
        ("Belapur", "Central Navi Mumbai hub with government offices and strong rail connectivity", 22000, "Transit"),
        ("Kharghar", "Growing Navi Mumbai town with corporate offices and modern residential projects", 23000, "Emerging"),
        ("Panvel", "Fast-growing sub-city with highway access and affordable housing", 19000, "Value"),
        ("Airoli", "Major eastern node with corporate campuses and solid transit access", 24000, "Office"),
        ("Juinagar", "Navi Mumbai suburb with strong rail links and affordable housing", 17000, "Budget"),
        ("Seawoods", "Modern Navi Mumbai node with malls, business parks, and metro connectivity", 26000, "Mixed"),
        ("Mahatma Phule Road", "Central Mumbai artery with busy retail, schools, and strong transit", 29000, "Transit"),
        ("Wadala", "Developing central district with emerging offices and metro access", 28000, "Emerging"),
        ("Mumbai Central", "Highly accessible central station area with strong job access", 30000, "Transit"),
        ("Grant Road", "Central south locality with markets, colleges, and solid transit links", 27000, "Family"),
        ("Shivaji Park", "Historic western precinct with parks, schools, and strong community values", 32000, "Family"),
        ("Girgaon", "South Mumbai residential pocket with cultural landmarks and transit access", 31000, "Lifestyle"),
        ("Pedder Road", "Upscale south-central address near business and lifestyle destinations", 42000, "Premium"),
        ("Ballard Estate", "Commercial district in south Mumbai with heritage office assets", 37000, "Office"),
    ],
    "Pune": [
        ("Koregaon Park", "Premium Pune address with dining, nightlife, green spaces, and strong corporate/IT presence", 30000, "Lifestyle"),
        ("Kothrud", "Established residential suburb with good schools, medical facilities and steady infrastructure growth", 22000, "Family"),
        ("Baner", "Growing IT corridor with modern housing, cafes, and easy access to Hinjewadi business parks", 24000, "IT"),
        ("Hinjewadi", "Major IT campus area with strong employment and emerging residential communities", 20000, "IT"),
        ("Shivajinagar", "Central Pune locality with strong connectivity, cultural landmarks, markets, and civic facilities", 26000, "CoreCity"),
        ("Aundh", "Mature residential area with good schools, healthcare, and strong retail options", 28000, "Family"),
        ("Wakad", "Rapidly growing IT and residential locality with strong highway access", 22000, "IT"),
        ("Pimple Saudagar", "Modern residential neighborhood popular with IT professionals and families", 23000, "Family"),
        ("Kharadi", "Fast-growing business and tech district with strong office demand", 25000, "IT"),
        ("Viman Nagar", "Residential and student-friendly neighborhood close to major offices and airport access", 24000, "Mixed"),
        ("Magarpatta", "Planned IT city with gated communities, strong amenities, and corporate campuses", 26000, "IT"),
        ("Camp", "Historic city center with strong transport access and business services", 25000, "CoreCity"),
        ("Karve Nagar", "Established residential market with good schools and civic infrastructure", 23000, "Family"),
        ("Warje", "Affordable suburb with good connectivity and growing residential options", 19000, "Value"),
        ("Sinhagad Road", "Hillside suburb with affordable housing and access to university campuses", 18000, "Budget"),
        ("Bavdhan", "Well-connected western suburb with modern housing and access to major roads", 22000, "Family"),
        ("Balewadi", "Sports and residential precinct with established communities and shopping", 23000, "Family"),
        ("Nigdi", "Planned suburb with good civic infrastructure near Pimpri-Chinchwad business districts", 20000, "Value"),
        ("Akurdi", "Affordable residential node with direct highway and rail connectivity", 18000, "Budget"),
        ("Pashan", "Quiet residential enclave near lakes, greenery, and good schools", 22000, "Family"),
        ("Kalyani Nagar", "Premium residential and shopping district with strong lifestyle appeal", 31000, "Premium"),
        ("Yerawada", "Central government and residential district with solid transit access", 21000, "Family"),
        ("Undri", "Rapidly developing southeast Pune suburb with new residential complexes", 19000, "Emerging"),
        ("Katraj", "South Pune suburb with strong educational institutions and affordable housing", 17000, "Value"),
        ("Dhankawadi", "Established residential localities near university campuses and transit routes", 20000, "Family"),
        ("Swargate", "Major transit hub with bus and metro connectivity and city-center access", 21000, "Transit"),
        ("Bibwewadi", "Affluent western suburb with a mix of residential and commercial pockets", 23000, "Lifestyle"),
        ("Narhe", "Affordable residential neighborhood with strong road access to western Pune", 18000, "Budget"),
        ("Manjari", "Industrial and residential corridor with affordable housing and good road access", 16000, "Value"),
        ("Mundhwa", "Rapidly appreciating suburb near Hadapsar and IT hubs", 22000, "Emerging"),
        ("Wagholi", "Expanding eastern suburb with new residential and industrial developments", 17000, "Value"),
        ("Kondhwa", "Popular suburban locality with good schools and easy highway connection", 21000, "Family"),
        ("Model Colony", "Central upscale neighborhood with leafy streets and established residences", 29000, "Premium"),
        ("Deccan Gymkhana", "College area with retail, cafes, and strong central access", 27000, "Lifestyle"),
        ("Lohegaon", "Airport-side residential and industrial locality with growing demand", 20000, "Transit"),
        ("Moshi", "Northern residential zone with improving transit and good value housing", 17000, "Value"),
        ("Dhayari", "Southwest Pune suburb with affordable housing and green surroundings", 16000, "Budget"),
        ("Bopodi", "Older suburb with good connectivity and demand from working professionals", 19000, "Value"),
        ("Salunke Vihar", "Growing residential zone near educational institutions and IT corridors", 18000, "Value"),
        ("Fatima Nagar", "Popular south-central locality with established residential communities", 21000, "Family"),
        ("Wadgaon Sheri", "Eastern suburb with mixed residential and office developments", 21000, "Mixed"),
        ("Keshav Nagar", "Accessible eastern pocket with good schools and moderate pricing", 18000, "Value"),
        ("NIBM Road", "Premium southeast corridor with residential towers and strong lifestyle services", 28000, "Premium"),
    ],
    "Nashik": [
        ("Nashik City", "City center locality with good connectivity, malls, and civic services", 17000, "CoreCity"),
        ("Panchavati", "Historic and tourist-facing district with strong retail and religious appeal", 16000, "Family"),
        ("Deolali", "Calm residential suburb with good schools and affordable housing", 14000, "Value"),
        ("Gangapur Road", "Busy arterial corridor with strong commerce and transport links", 15000, "Transit"),
        ("Satpur", "Industrial and residential node with affordable homes and steady infrastructure", 13000, "Value"),
        ("Makhmalabad", "Growing residential area with schools, hospitals, and improved transit", 14500, "Family"),
        ("Shrirampur", "Commercial suburb with strong connectivity to Nashik city and industrial centers", 12000, "Budget"),
        ("Cidco", "Planned township with good infrastructure, education, and transit access", 15000, "Family"),
        ("Ambad", "Industrial and residential zone with competitive rents and steady transport", 12500, "Budget"),
        ("Trimbak Road", "Key access corridor with connectivity to northern Nashik neighborhoods", 13500, "Transit"),
        ("Sharanpur Road", "Developing residential corridor with moderate prices and good schools", 13000, "Value"),
        ("Anju Baugh", "Affordable neighborhood with strong local commerce and transport", 11500, "Budget"),
        ("Dwarka", "Emerging residential pocket with new housing near central Nashik", 14000, "Value"),
        ("Vasna", "Established residential zone with parks, schools, and steady amenities", 14500, "Family"),
        ("Indira Nagar", "Popular mid-range locality with good access to business districts", 15000, "Family"),
        ("Gandharvan Phata", "Growing suburban area with improving infrastructure and housing", 12000, "Value"),
        ("Pathardi Phata", "Well-connected eastern gateway locality with affordable accommodation", 12500, "Budget"),
        ("Nandurbar", "Residential zone near major road links and local markets", 13000, "Value"),
        ("Gangapur", "Commercial hub near the ring road with strong transport access", 13500, "Transit"),
        ("Kale", "Up-and-coming residential sector with good value and transport access", 11000, "Budget"),
    ],
    "Kolhapur": [
        ("Karveer", "Large urban area with good civic amenities, shopping districts and a strong local economy", 15000, "Family"),
        ("Rukadi", "Residential suburb with manufacturing clusters, quiet streets and approachable pricing", 13000, "Value"),
        ("Kagal", "Industrial town near Kolhapur with growing residential pockets and favorable housing costs", 14000, "Value"),
        ("Shiroli", "Emerging residential area near educational institutions and expanding commercial zones", 16000, "Emerging"),
        ("Rajarampuri", "Affluent residential locality with parks, schools and established housing", 17000, "Family"),
        ("Tarabai Park", "Central neighborhood with good shopping, healthcare and heritage appeal", 15500, "Family"),
        ("Shahupuri", "Historic city area with markets, temples, and strong local culture", 14500, "CoreCity"),
        ("Ruikar Colony", "Quiet residential colony with good schools and community services", 13500, "Family"),
        ("Nagala Park", "Leafy, established township with decent civic infrastructure", 14000, "Family"),
        ("Kasaba Bawada", "Busy commercial and residential sector with strong local markets", 13000, "Transit"),
        ("Sambhaji Nagar", "Well-connected locality with affordable housing and strong civic services", 13500, "Value"),
        ("Ujalaiwadi", "Residential area popular with families seeking calm neighborhoods", 13200, "Family"),
        ("Mangalwar Peth", "Historic mixed-use area with markets, temples, and local transport links", 12800, "CoreCity"),
        ("Laxmipuri", "Moderate residential locality with good access to city center amenities", 13000, "Value"),
        ("Shahu Nagar", "Planned residential layout with schools and civic spaces", 13700, "Family"),
        ("Padambhai Nagar", "Quiet western township with growing housing demand", 12500, "Value"),
    ],
    "Sangli": [
        ("Sangli City", "Main city hub with established markets, healthcare and accessible educational facilities", 15000, "CoreCity"),
        ("Miraj", "Cultural town with strong railway connectivity, medical centers, and quieter residential zones", 14000, "Family"),
        ("Kupwad", "Industrial and residential locality with affordable housing and a local workforce community", 12000, "Value"),
        ("Palus", "Smaller municipal town with agriculture-led economy, calm streets, and low living costs", 11000, "Value"),
        ("Jaysingpur", "Growing town with textile markets, education institutions, and reasonable living costs", 13000, "Value"),
        ("Vishrambag", "Historic central neighborhood with temples, trading streets, and strong community life", 13500, "CoreCity"),
        ("Madhavnagar", "Residential area with good schools and balanced transit access", 13000, "Family"),
        ("Khanbhag", "Commercial residential sector near the river with accessible markets", 12500, "Value"),
        ("Ganapati Peth", "Busy market area with strong retail and local transit options", 12800, "Transit"),
        ("Mission Compound", "Central educational and residential precinct with calm pockets", 13200, "Family"),
        ("Shahupuri", "Heritage district with old town charm and strong local commerce", 12700, "CoreCity"),
        ("Laxmi Road", "Primary shopping street and central transport corridor", 13800, "Transit"),
        ("Navkars", "South city locality with affordable housing and good local services", 12100, "Value"),
    ],
    "Satara": [
        ("Satara City", "Historic city center offering affordable living, good safety, and growing local commerce", 14000, "CoreCity"),
        ("Koregaon", "Quiet small-town neighborhood with easy access to Satara’s schools and agriculture markets", 12000, "Value"),
        ("Wai", "Scenic riverside town known for heritage sites, quieter living, and tourism-driven services", 13000, "Lifestyle"),
        ("Patan", "Smaller town with affordable housing, strong local culture, and calm residential neighborhoods", 11000, "Value"),
        ("Powai Naka", "Busy market and residential locality with strong local transport and services", 11500, "Transit"),
        ("Shahupuri", "Established shopping and residential area with a strong community feel", 11800, "CoreCity"),
        ("Godoli", "Residential suburb with growing housing demand and calm streets", 11300, "Value"),
        ("Karad Road", "Peripheral road-side locality with affordable homes and good highway access", 10800, "Budget"),
        ("Mangalwar Peth", "Local market area with traditional shops and good connectivity", 11000, "CoreCity"),
        ("Sadar Bazar", "Central market locality with strong retail activity and city links", 11200, "Transit"),
        ("Usha Nagar", "Family-friendly residential neighborhood with steady amenities", 11500, "Family"),
        ("Vaduj", "Railway-side locality with good affordability and local commerce", 10500, "Budget"),
    ],
}

category_metrics = {
    "Premium": {"job": 9.0, "health": 8.5, "transport": 8.0, "safety": 8.0, "pollution": 6.5, "life": 9.0, "density": 8.0},
    "UltraPremium": {"job": 9.5, "health": 9.0, "transport": 8.5, "safety": 8.5, "pollution": 6.5, "life": 9.5, "density": 9.0},
    "IT": {"job": 9.0, "health": 8.0, "transport": 7.5, "safety": 7.5, "pollution": 6.5, "life": 8.5, "density": 7.5},
    "Office": {"job": 9.0, "health": 8.0, "transport": 8.5, "safety": 7.5, "pollution": 7.0, "life": 7.5, "density": 8.5},
    "Family": {"job": 7.5, "health": 8.0, "transport": 7.0, "safety": 8.0, "pollution": 6.0, "life": 8.0, "density": 7.0},
    "Transit": {"job": 7.5, "health": 7.5, "transport": 8.5, "safety": 7.5, "pollution": 7.5, "life": 7.5, "density": 8.0},
    "Mixed": {"job": 7.5, "health": 7.5, "transport": 7.5, "safety": 7.5, "pollution": 7.0, "life": 7.5, "density": 7.5},
    "Value": {"job": 6.5, "health": 7.0, "transport": 7.0, "safety": 7.5, "pollution": 7.5, "life": 6.5, "density": 6.5},
    "Budget": {"job": 6.0, "health": 6.5, "transport": 6.5, "safety": 7.0, "pollution": 7.5, "life": 6.0, "density": 6.0},
    "Emerging": {"job": 7.0, "health": 7.0, "transport": 7.0, "safety": 7.0, "pollution": 7.5, "life": 7.0, "density": 6.5},
    "CoreCity": {"job": 8.0, "health": 7.5, "transport": 8.0, "safety": 7.5, "pollution": 7.0, "life": 7.5, "density": 8.0},
}

prefix_map = {"Mumbai": "MUM", "Pune": "PUN", "Nashik": "NAS", "Kolhapur": "KOL", "Sangli": "SAN", "Satara": "STA"}

records = []
for city, localities in city_localities.items():
    prefix = prefix_map[city]
    for idx, (name, description, avg_rent, category) in enumerate(localities, start=1):
        metrics = category_metrics.get(category, category_metrics["Mixed"])
        record = {
            "id": f"{prefix}{idx:03d}",
            "name": name,
            "city": city,
            "state": CITY,
            "avgRent": avg_rent,
            "jobIndex": metrics["job"],
            "hospitalRating": metrics["health"],
            "transportScore": metrics["transport"],
            "safetyScore": metrics["safety"],
            "pollutionIndex": metrics["pollution"],
            "lifestyleScore": metrics["life"],
            "populationDensity": metrics["density"],
            "description": description,
        }
        records.append(record)

output_path = Path("data/localities.json")
output_path.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"Wrote {len(records)} locality entries to {output_path}")
